export const filters = ['all', 'aircrafts', 'airports', 'misc', 'utilities'];

export const addons = [
  {
    image: "/images/eham-cover.jpg",
    title: "Amsterdam Schiphol Airport",
    icao: 'EHAM',
    developer: "FlyTampa",
    version: "1.0.0",
    country: 'nl',
    date: 'October 11, 2023',
  },
  {
    image: "/images/eghi-cover.jpg",
    title: "Southampton Airport",
    icao: 'EGHI',
    developer: "iniBuilds",
    version: "1.0.1",
    country: 'gb',
    date: 'October 11, 2023',
  },
  {
    image: "/images/kbos-cover.jpg",
    title:
    "General Edward Lawrence Logan International / Boston Logan Airport",
    icao: 'KBOS',
    developer: "FlyTampa",
    version: "1.6.0",
    country: 'us',
    date: 'October 9, 2023',
  },
  {
    image: "/images/ymml-cover.jpg",
    title: "Melbourne Airport",
    icao: 'YMML',
    developer: "Orbx",
    version: "1.0.1",
    country: 'au',
    date: 'October 6, 2023',
  },
  {
    image: "/images/egss-cover.jpg",
    title: "London Stansted Airport",
    icao: 'EGSS',
    developer: "iniBuilds",
    version: "1.0.6",
    country: 'gb',
    date: 'October 6, 2023',
  },
  {
    image: "/images/phnl-cover.jpg",
    title: "Honolulu / Daniel K. Inouye International Airport",
    icao: 'PHNL',
    developer: "iniBuilds",
    version: "1.0.1",
    country: 'us',
    date: 'October 2, 2023',
  },
  {
    image: "/images/epgd-cover.jpg",
    title: "Gdansk Lech Walesa Airport",
    icao: 'EPGD',
    developer: "Drzewiecki Design",
    version: "1.2.0",
    country: 'pl',
    date: 'September 29, 2023',
  },
  {
    image: "/images/pmdg738-cover.jpg",
    title: "Boeing 737-800",
    developer: "PMDG",
    version: "3.0.72",
    date: 'September 28, 2023',
  },
  {
    image: "/images/eddm-cover.jpg",
    title: "Munich Airport",
    icao: 'EDDM',
    developer: "Sim Wings",
    version: "2.0.0",
    country: 'de',
    date: 'September 25, 2023',
  },
];
